services:
  mysql-primary:
    image: mysql:8.0.40
    container_name: mysql-primary
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3301:3306"
      - "33061:33061"
    volumes:
      - ./mysql-primary/data:/var/lib/mysql
      - ./conf.d/:/etc/mysql/conf.d
      - ./init/primary-init:/docker-entrypoint-initdb.d
    command:
      - --server-id=1
      - --loose-group_replication_local_address=mysql-primary:33061
    networks:
      - bridge-network

  mysql-secondary:
    image: mysql:8.0.40
    container_name: mysql-secondary
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3302:3306"
      - "33062:33061"
    volumes:
      - "./mysql-secondary/data:/var/lib/mysql"
      - "./conf.d:/etc/mysql/conf.d"
      - "./init/secondary-init:/docker-entrypoint-initdb.d"
    depends_on:
      - mysql-primary
    command:
      - --server-id=2
      - --loose-group_replication_local_address=mysql-secondary:33061
    networks:
      - bridge-network

#  proxysql:
#    image: proxysql/proxysql:latest
#    container_name: proxysql
#    environment:
#      MYSQL_ROOT_PASSWORD: 1234
#    ports:
#      - "6033:6033"  # ProxySQL의 MySQL 접속 포트
#      - "6032:6032"  # ProxySQL Admin 포트
#    networks:
#      - bridge-network
#    depends_on:
#      - mysql-primary
#      - mysql-secondary
#    volumes:
#      - ./proxysql/proxysql.conf:/etc/proxysql.cnf
#    command: /bin/bash -c "proxysql --proxysql.conf-file=/etc/proxysql.cnf"

#  mysql-sh:
#    image: mysql/mysql-shell:8.0.32
#    container_name: mysql-sh
#    entrypoint: [ "mysqlsh", "--uri", "root@mysql-primary:3306" ]
#    networks:
#      - bridge-network
#    stdin_open: true
#    tty: true
#    depends_on:
#      - mysql-primary
#      - mysql-secondary

  mysql-router:
    image: mysql/mysql-router:8.0.32
    container_name: mysql-router
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_HOST=mysql-primary
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_INNODB_CLUSTER_MEMBERS=2
      - MYSQL_CREATE_ROUTER_USER=0
    ports:
      - "6446:6446"
      - "6447:6447"
    volumes:
      - ./mysql-router/proxysql.conf/router.conf:/etc/mysql-router.conf
    depends_on:
      - mysql-primary
      - mysql-secondary
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge